### ISSUE TITLE
Register system-config-printer on gapplication to avoid launch of multiple instances

### ISSUE THREAD

**Issue by tillkamppeter** [OpenPrinting/system-config-printer#103]
If you start system-config-printer while it is already running a second instance of system-config-printer is started, whereas it would be much more convenient if we simply pull the window of the running instance to the front.
Other desktop applications use gapplication and so avoid duplicate instances. The second and further calls of the app then simply focus the window of the first instance.

**Comment by zdohnal** [comment]
But I'll see if I can come with a configure option, which could set such behavior if requested.

**Comment by saitam1** [comment]
The argument "is it a convention...?" is bad. Do you want e.g. Spotify to open a new instance as soon as you click on it to check which song is playing currentls? What is the use of the current behaviour? 
Please change it.

**Comment by zdohnal** [comment]
@saitam1 Other way - why do you click again on the icon, when you have already a window opened? When I want to open other window, then I'll click on the icon. 
If there isn't any norm or policy for it, then it is a matter of preference. I'll prefer the way mentioned above, but if there is a way to make it configurable during compiling, then I can look into it. Feel free to submit a patch.

**Comment by zdohnal** [comment]
I'm closing the issue because the app behaves in intended way.
