### ISSUE TITLE
The IPP Everywhere "driver" and system-config-printer

### ISSUE THREAD

**Issue by debiantriage** [OpenPrinting/system-config-printer#125]
CUPS 2.2.9 now supports listing IPP Everywhere in its web interface. At present, lpadmin, the web interface and cups-browsed support using either  the CUPS PPD generator or the cups-filters PPD generator. The odd one  out of the printer/queue setup utilities appears to be s-c-p.

Please enable s-c-p to emulate the behaviour of the other three utilities.

Thanks,

Brian.

**Comment by debiantriage** [comment]
> Please enable s-c-p to emulate the behaviour of the other three utilities.

I intended to say that I was pointed here from

https://lists.debian.org/debian-printing/2018/11/msg00102.html

-- 
Brian.

**Comment by zdohnal** [comment]
Hi Brian,

I noticed this selection (CUPS/cups-browsed PPD generators) in cups-browsed config, but didn't investigated deeply how it is done. I'll look into cups web ui how it is precisely done and what can be currently done in s-c-p...
I think adding this behavior will need several changes in python-cups project too and then used in s-c-p... I am afraid I currently don't have enough time to focus the matter properly, I'm sorry...

**Comment by zdohnal** [comment]
@debiantriage Can I somehow see these features when I do not have IPP Everywhere printer myself? I have only HP printer from 2009...

**Comment by tillkamppeter** [comment]
You can emulate an IPP Everywhere printer using the ippserver utility which comes with CUPS. Run the utility on a re,mote machine or a VM.

**Comment by zdohnal** [comment]
Hi Brian,
system-config-printer is in maintenance mode and other means of configuring printers are available (CUPS web ui, cups-browsed) or on their way (GUI application for IPP system service), so I don't plan implementing the 'everywhere' model in s-c-p.
If there will be a pull request, I'll review it and add it to the project.
