### ISSUE TITLE
 I don't find my printer pilot

### ISSUE THREAD

**Issue by ghost** [OpenPrinting/system-config-printer#131]
I search for Epson XP-540 series but it didn't exist

**Comment by zdohnal** [comment]
Hi!
would you mind telling me more? What do you mean by 'search for Epson XP-540'? Do you mean:

1) you have Epson XP-540 printer and you tried to search for the printer during adding a new printer
- if that's the case, please check if the printer can be found by 'sudo lpinfo -l -v' - if it does not, then problem is not in s-c-p, but in CUPS or in printer settings.

2) you wanted to find driver for Epson XP-540 printer in database in s-c-p - if that's the case, contents of the database are supplied by printer driver packages as hplip, gutenprint, foomatic, not s-c-p.

**Comment by zdohnal** [comment]
Closed due inactivity.
