### ISSUE TITLE
German (DE) Translation typo

### ISSUE THREAD

**Issue by dimebag88** [OpenPrinting/system-config-printer#145]
"Add"-Button in German says "H**I**nzufügen" instead of "Hinzufügen" (second letter of the word is also capitalized).

**Comment by zdohnal** [comment]
Hi,
thank you for reporting the issue. Hmm... I do not see any 'HInzufügen' in po/de.po, which stores the german translation.
Do you compile system-config-printer on your own or do you use packaged one from specific OS?

**Comment by dimebag88** [comment]
Hi,
thanks for the quick reply. Just checked the version of system-config-printer and it seems to be the forked version: https://github.com/zdohnal/system-config-printer/.
Sorry for the wrong report. 

BTW: I use the packaged version; OS is Arch Linux with gnome 3.34/xfce 4.14 - issue is not present on Ubuntu-based distros.

Best regards,
Michael

**Comment by zdohnal** [comment]
Ok, no problem, please report the issue to Arch Linux folks. Please tell them they should change the upstream source, I moved system-config-printer from my personal github to OpenPrinting organization.
