### ISSUE TITLE
please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [OpenPrinting/system-config-printer#148]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:

* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:

* For github and gitlab hosted projects, Weblate open pull request. For other git hosting, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by Jibec** [comment]
could solve #114

**Comment by zdohnal** [comment]
Hi @Jibec 

thank you for letting me know! What should I do to migrate to Weblate since Zanata is deprecated? I looked into [1], but the steps are probably only for those who wants to translate.

I use 'master' branch for developing and Zanata project is locked now.

**Comment by Jibec** [comment]
Le 2020-01-09 14:20, zdohnal a écrit :
> thank you for letting me know! What should I do to migrate to Weblate 
> since Zanata is deprecated?

Please delete from your repository translations files without 
translation (use file size and or `pocount` from translate toolkit).
I'll do first configuration of weblate, and make you admin so you can 
tune it in the future (please connect to the translation platform so I 
can see you in users).

**Comment by zdohnal** [comment]
> Le 2020-01-09 14:20, zdohnal a écrit :
> thank you for letting me know! What should I do to migrate to Weblate since Zanata is deprecated?
> Please delete from your repository translations files without translation (use file size and or `pocount` from translate toolkit).

Do you mean .po files which do not have any translated strings/words? All languages seems to have some strings translated according 'pocount' results.

> I'll do first configuration of weblate, and make you admin so you can tune it in the future (please connect to the translation platform so I can see you in users).

Meaning https://translate.stg.fedoraproject.org/ as translation platform?

**Comment by Jibec** [comment]
Yes to both questions

**Comment by zdohnal** [comment]
Ad 1 - so then I'm done, any .po file is not completelu untranslated.

Ad 2 - I have FAS account, so you should be able to add my nick to the project (the same nick as at github) - do I need to be logged in right now? Seems strange if it is the case.

**Comment by Jibec** [comment]
configuration is done: 
https://translate.stg.fedoraproject.org/projects/system-config-printer/master/ 



ALL_LINGUAS variable will be updated by Weblate 
https://docs.weblate.org/en/weblate-3.10.1/admin/addons.html#addon-weblate-gettext-configure

PO files will be updated by Weblate when POT is updated

Weblate will use Git Squash by author to limit the number of commits

**Comment by zdohnal** [comment]
AFAIK it is done, closing the ticket.
