### ISSUE TITLE
Localization guide: Source string location

### ISSUE THREAD

**Issue by Jibec** [OpenPrinting/system-config-printer#150]
In gettext, the source string location is relative to the place the script to execute the pot was generated.

a source string location could contain "../" and thus, impact the URL.

As an example:
`https://github.com/OpenPrinting/system-config-printer/blob/master/../asyncipp.py#L474`
will become
`https://github.com/OpenPrinting/system-config-printer/blob/asyncipp.py#L474`
and lead to a 404 error page.

I would expect: a line in Localization guide that checks if context works as expected.
A warning sign in case of error.
An email in case of error detection.

When trigger this check? Each time weblate repo is updated.
What to check: three values (first, middle, last)
Results is a warning if one of the URL failed

thanks a lot for your help

**Comment by zdohnal** [comment]
Hi @Jibec ,

I'm not quite sure what to take of the issue - it seems like a report for weblate, not system-config-printer.

**Comment by Jibec** [comment]
Oh, true, sorry about that! You can close it.

**Comment by zdohnal** [comment]
Np, thank you for letting me know!
