### ISSUE TITLE
 "Out of Paper" message is NOT displayed. 

### ISSUE THREAD

**Issue by 49studebaker** [OpenPrinting/system-config-printer#152]
1) Ubuntu 19.10
2) system-config-printer 1.5.11
3) system-config-printer detected my HP Laserjet 1020. I printed a page, and it was added to the print queue. The page did not print and the print job disappeared from the print queue. I downloaded foo2zjs.tar.gz from http://foo2zjs.rkkda.com/ and followed the instructions. I was able to get my printer to successfully print pages. When my HP Laserjet 1020 is out of paper. The green light on the printer changes to a blinking orange light. An "Out of Paper" message with a retry button, should have been displayed.
4) An "Out of Paper" message with a retry button, was NOT displayed.

**Comment by zdohnal** [comment]
Hi,
the s-c-p behavior depends on what CUPS knows and CUPS depends on reports from backend (binary which communicate with device).
Can you see the message in CUPS web interface in 'Printers' tab? If there is no message about out-of-paper, CUPS know nothing about the situation, so s-c-p does not know neither.
Usually, the functionality about reporting such messages is implemented only in 'ipp' backend.

**Comment by 49studebaker** [comment]
I clicked "Settings", "Devices", "Printers", "Additional Printer Settings...". I then opened "View Print Queue" and "Properties". I tried printing with no paper. The printer State changed from "Idle" to "Processing - Sending data to printer". No "Out of Paper (retry_button)" message was displayed. If I right click on Job 75 and then click "Reprint", the printer prints again. Refer to attached images.


Later, I found that the web interface can be accessed at:

http://localhost:631/printers/

I turned off the printer and turned it on again. The web interface status is "Idle". I tried printing but the status did not change. I turned off/on the printer. After printing, I quickly pressed the refresh button in Firefox. The Status changed from "Idle" to "Processing - Sending data to printer" and then back to "Idle". Attached "error_log" and "access_log" which are from the web interface.

![1_before_printing](https://user-images.githubusercontent.com/18037226/73125622-792a7700-3f6e-11ea-851c-0dbcea316ee1.png)
![2_after_clicking_print_test_page](https://user-images.githubusercontent.com/18037226/73125633-95c6af00-3f6e-11ea-988e-f3588f76f8ab.png)
![3_page_did_not_print_orange_light_flashes](https://user-images.githubusercontent.com/18037226/73125644-c3abf380-3f6e-11ea-9b88-db3c715d5098.png)
![4_job_attributes](https://user-images.githubusercontent.com/18037226/73125663-0372db00-3f6f-11ea-8029-3a77b5983dc0.png)

[access_log.txt](https://github.com/OpenPrinting/system-config-printer/files/4112430/access_log.txt)
[error_log.zip](https://github.com/OpenPrinting/system-config-printer/files/4112431/error_log.zip)

**Comment by zdohnal** [comment]
Your printer does not generate any message about out of paper to CUPS, so s-c-p does not know anything about it too.
Closing as third-party.
