### ISSUE TITLE
 In printer settings, add "Manual Double Sided". Print odd pages first, then display message to remove and reinsert pages, then horizontally rotate and print even numbered pages in descending order.

### ISSUE THREAD

**Issue by 49studebaker** [OpenPrinting/system-config-printer#153]
1) Ubuntu 19.10
2) system-config-printer 1.5.11
3) Inability to manually print on both side of paper.
4) Ability to manually print on both side of paper.

If print page count is 1, then do not display a message to remove and reinsert page.

**Comment by zdohnal** [comment]
Hi,
I'm not sure what's the issue you are reporting - what you wrote in desc is how manual double-sided printing works.
Would you mind clarifying what the issue is?

**Comment by 49studebaker** [comment]
There is not a "manual double-sided" printing option in system-config-printer settings. In Windows, there is a "manual double-sided" print option.

Printer: HP Laserjet 1020
Driver: http://foo2zjs.rkkda.com/

**Comment by zdohnal** [comment]
There is no such option in driver itself, so nothing to show by s-c-p. Sorry.
