### ISSUE TITLE
Disabling job history renders cups unusable

### ISSUE THREAD

**Issue by es20490446e** [OpenPrinting/system-config-printer#160]
HOW TO REPRODUCE:
- On server settings, disable job history.

RESULT:
- The cups daemon crashes.
- The cups service no longer initializes on system startup.
-  System Config Printer no longer allows enabling job history.

SYSTEM INFO:
- print-settings 1.5.12
- cups 2.3.1

**Comment by tillkamppeter** [comment]
Please have a look ate your `/etc/cups/cupsd.conf` file. It maybe corrupted by the attempt of the CUPS daemon following a command to change its configuration. This is a bug in CUPS. see apple/cups#5744.

**Comment by tillkamppeter** [comment]
If you are using Ubuntu Focal or Debian unstable, make sure to get CUPS 2.3.1-9.
