### ISSUE TITLE
udev-configure-printer: Coredump when powering on or starting PC with printer on

### ISSUE THREAD

**Issue by Englishman100** [OpenPrinting/system-config-printer#161]
Printer is Canon iP4600 connected via a USB port (fails on all ports)

Error can be reproduced by powering on the PC with the printer powered on or by powering on the printer after the PC has booted into Linux.

system-config printer version 1.5.12-2

Trace as follows:
[Printer.txt](https://github.com/OpenPrinting/system-config-printer/files/4244079/Printer.txt)

**Comment by zdohnal** [comment]
Hi,
 
> system-config printer version 1.5.12-2

It seems like NVR of package, not project version. What OS do you have? There was additional fix for the segfault.

If you are not able to reproduce with current master, please file a ticket to your distro.

**Comment by Englishman100** [comment]
Apologies, was the Arch Linux package number. I have checked the Arch source and it was built directly from OpenPrinting /system-config-printer on 4th November 2019. 
I'm new to GitHub so could you point me to the fix if after this date. Thank you!

**Comment by zdohnal** [comment]
You can check 'View changes' at https://www.archlinux.org/packages/extra/x86_64/system-config-printer/ - as you can see there was no s-c-p related update after rebase to 1.5.12, so the current fixes are not backported.
The fixes for the issue are commits https://github.com/OpenPrinting/system-config-printer/commit/b9289dfe105bdb502f183f0afe7a115ecae5f2af and https://github.com/OpenPrinting/system-config-printer/commit/cf9903466c1a2d18a701f3b5e8c7e03483e1244d .
