### ISSUE TITLE
PPD with custom options

### ISSUE THREAD

**Issue by cbix** [OpenPrinting/system-config-printer#17]
I have this in my PPD:

```
*% Base JCL Authentication option
*JCLOpenUI JCLAuthenticationUser/Login Benutzername: PickOne
*OrderDependency: 10 JCLSetup *JCLAuthenticationUser
*DefaultJCLAuthentication: {Username=""}
*JCLAuthenticationUser None/Kein: "@PJL SET KMUSERNAME = <22><22> <0A>"
*JCLCloseUI: *JCLAuthenticationUser

*% Custom JCL Authentication option
*CustomJCLAuthenticationUser True: "@PJL SET KMUSERNAME = <22>\1<22> <0A>"
*ParamCustomJCLAuthenticationUser Username/Benutzername: 1 string 1 99
```

Then, in the printer default settings dialog, when selecting "Custom", there should be an input field. Try with the CUPS web GUI, it's working there.

**Comment by ilmaisin** [comment]
+1 for this. I work on a CUPS "driver" that prints to PDF and sends it via email. It would benefit from this, see ilmaisin/cupsmailprinter#1. Assuming I solve the issue in my project first (and assuming my project will finish at all :-) I will have to resort to asking my users to work around this issue by using the web UI.

**Comment by cyanogenic** [comment]
+1 for this in 2021

**Comment by zdohnal** [comment]
PPD Drivers are deprecated and CUPS itself will stop supporting them in near future, so this won't go into s-c-p.
