### ISSUE TITLE
Lack of python-smbc fails silently

### ISSUE THREAD

**Issue by mirh** [OpenPrinting/system-config-printer#174]
I suppose also handling the case where it isn't available cannot hurt..
But if you just let the SAMBA entry and everything where they normally are, it's just recipe for problems. 
I just lost one hour trying to understand why clicking the browse button didn't do anything.

**Comment by zdohnal** [comment]
Hi @mirh,

there are two ways how it is handled now:
1) everytime you click on 'Browse' it triggers PackageKit with notification that there is an additional software to be installed. At least how it works for me in Fedora 31 - what OS do you use and is there PackageKit available?
2) when you focus on 'Verify', there should appear the text - 'Verification requires pysmbc module' - which is not shown right now in F31, so I'll look into why it isn't.

**Comment by mirh** [comment]
I'm on Manjaro and packagekit isn't installed (by default at least).

**Comment by zdohnal** [comment]
Ok, so now it will work like this:

When pysmbc is not installed:
- there will be a text about requiring pysmbc when you focus on 'Browse' or 'Verify' (when uri, password and user name is supplied) buttons, but they remain sensitive
- when you click on the active button 'Browse' or 'Verify' (when it is active), s-c-p will try to call packagekit and install python3-smbc
- 'tip' text when you focus on the button will go away only when python3-smbc is installed during the start of s-c-p

When pysmbc is installed:
- no text tip when focused on 'Browse' or 'Verify'

**Comment by zdohnal** [comment]
Fixed in commit 5f243b36
