### ISSUE TITLE
Applet does not terminate at end of X desktop session

### ISSUE THREAD

**Issue by tillkamppeter** [OpenPrinting/system-config-printer#175]
See [Ubuntu bug #1877528](https://bugs.launchpad.net/ubuntu/+source/system-config-printer/+bug/1877528):
```
This concerns system-config-printer 1.5.12-0ubuntu1 in Ubuntu focal.

I log into the Xfce desktop, and then logout. The screen returns to the LightDM login screen.

A few minutes later, "loginctl list-sessions" shows the following:

    SESSION UID USER SEAT TTY
          9 0 root
         c2 1000 skunk seat0
         c3 116 lightdm seat0

    3 sessions listed.

Output from "loginctl session-status c2":

    c2 - skunk (1000)
               Since: Fri 2020-05-08 03:09:05 EDT; 9min ago
              Leader: 2530
                Seat: seat0; vc7
             Display: :0
             Service: lightdm; type x11; class user
             Desktop: xubuntu
               State: closing
                Unit: session-c2.scope
                      └─2856 /usr/bin/python3 /usr/share/system-config-printer/applet.py

This process sticks around forever until I kill it, or its parent "systemd --user" process. Only then does the session disappear from list-sessions.

When I run "session-status" while I'm logged in, I see a list of nearly 30 desktop-related processes. All of them except this one go away on logout. This one should too.
```
This got also [reported to Debian](https://bugs.debian.org/863227) 3 years ago.

**Comment by zdohnal** [comment]
Hi @tillkamppeter ,

thank you for reporting the issue!

Are you able to reproduce the issue? I tried to reproduce on Fedora 32 with Xfce desktop (s-c-p and s-c-p-applet installed) but I have no dangling session due s-c-p-applet.

I'm downloading Ubuntu 20 now and I'll try it there with Xfce.

**Comment by tillkamppeter** [comment]
I have simply forwarded a bug report to Ubuntu. I did not observe the problem by myself.

**Comment by zdohnal** [comment]
So it is Ubuntu specific issue - now I'm able to reproduce in Xubuntu 20.

**Comment by zdohnal** [comment]
Xubuntu traceback after connecting to the hanging process:

```
(gdb) py-bt
Traceback (most recent call first):
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 497, in run
    super(MainLoop, self).run()
  File "/usr/share/system-config-printer/applet.py", line 355, in run
    self.loop.run ()
  File "/usr/share/system-config-printer/applet.py", line 3537, in <module>
```

**Comment by zdohnal** [comment]
I was able to reproduce in Fedora after switch from gdm to lightdm. There are more apps which hangs there too (in Fedora and Ubuntu), so it is either problem of more apps or a problem with desktop manager.
What dbus upstream says makes sense in https://bugs.freedesktop.org/show_bug.cgi?id=94508#c11 and can be done, but other question is why it works with gdm but not with lightdm.

**Comment by zdohnal** [comment]
Seems to be desktop manager related - applet doesn't hang in gdm and lxdm, hangs in sddm, kdm, lightdm.

**Comment by iskunk** [comment]
Hi @zdohnal, I am the original reporter of the Ubuntu bug.

(@tillkamppeter, thank you for bringing the bug here!)

It is possible that there is some systemd involvement here as well. Just a couple comments to make:
> I was able to reproduce in Fedora after switch from gdm to lightdm. There are more apps which hangs there too (in Fedora and Ubuntu), so it is either problem of more apps or a problem with desktop manager.

Are these processes as listed by `ps`, or `loginctl session-status`? The former typically shows a large number of desktop-related processes lingering after logout, but the latter only shows s-c-p. If I manually kill s-c-p, then all the other processes go away. I take this to mean that the other processes are waiting for `systemd --user` to kill them, but `systemd --user` is waiting on s-c-p to "finish" in some way first.

I don't understand this strange world of dbus and systemd, so there's not much more I can say. But I'll be happy to test or try something if you've got it...

**Comment by zdohnal** [comment]
@iskunk 
> Are these processes as listed by `ps`, or `loginctl session-status`? 
In my case it is loginctl session-status.

> If I manually kill s-c-p, then all the other processes go away.
Unfortunately, it is not in my case in F32 (using kdm) - if I kill python process which runs s-c-p-applet, other processes hang, see:

```
[user@localhost ~]$ loginctl session-status 1
1 - user (1000)
           Since: Wed 2020-05-13 14:20:18 CEST; 41s ago
          Leader: 1095
            Seat: seat0; vc1
         Display: :0
         Service: kdm; type x11; class user
           State: closing
            Unit: session-1.scope
                  ├─1441 /usr/bin/gpg-agent --sh --daemon --write-env-file /home/user/.cache/gpg-age>
                  ├─1560 /usr/bin/python3 /usr/share/system-config-printer/applet.py
                  ├─1576 abrt-applet --gapplication-service
                  ├─1587 /usr/libexec/tracker-miner-fs
                  ├─1658 /usr/libexec/tracker-miner-rss
                  └─1712 /usr/libexec/geoclue-2.0/demos/agent
```
Then after killing process 1560:

```
[user@localhost ~]$ loginctl session-status 1
1 - user (1000)
           Since: Wed 2020-05-13 14:20:18 CEST; 1min 1s ago
          Leader: 1095
            Seat: seat0; vc1
         Display: :0
         Service: kdm; type x11; class user
           State: closing
            Unit: session-1.scope
                  ├─1441 /usr/bin/gpg-agent --sh --daemon --write-env-file /home/user/.cache/gpg-age>
                  ├─1576 abrt-applet --gapplication-service
                  ├─1587 /usr/libexec/tracker-miner-fs
                  ├─1658 /usr/libexec/tracker-miner-rss
                  └─1712 /usr/libexec/geoclue-2.0/demos/agent
```

**Comment by zdohnal** [comment]
I looked into possibility to have print-applet as systemd user service.

Unfortunately, print-applet connects to both dbuses - system and user - so IIUC when print-applet would be user service, it cannot connect to system dbus and vice versa.

It would need to divide the applet into two binaries each connecting to different dbus and create service files for them, which IMO is not worth to focus on for an applet which is not used by several major desktop environments (GNOME, Cinnamon, KDE) and the applet hangs only with specific desktop managers on those desktop environments, which the applet actually uses.

However, if a patch fixing the issue will come, I'll review it and merge based on review's result.

**Comment by usul0184** [comment]
I know this is closed and won't be fixed, but just wanted to mention that this issue also occurs on my system: Manjaro Xfce 20.1 using LightDM.  Curious if anyone knows whether there is some downside to just force killing print-applet on logout, such as through `KillUserProcesses` in `logind.conf`?

**Comment by Monsterovich** [comment]
I have the same issue on Linux Mint 20.2 (Xfce). The easiest solution is to kill applet.py process on logout.

![изображение](https://user-images.githubusercontent.com/3750982/143255149-10690883-5c8f-439a-be4b-591c7013aa16.png)

**Comment by Monsterovich** [comment]
@zdohnal Can you kill the print applet process if the parent process (ex. xfce4-session) dies? I'd provide the patch, but I don't know how to do this correctly in python.

**Comment by zdohnal** [comment]
Note:

the PR @Monsterovich has provided mitigates the issue - no new applets will be created, but the old applet will linger until system is restarted.
