### ISSUE TITLE
Protocol handle is misplaced in RTL

### ISSUE THREAD

**Issue by yarons** [OpenPrinting/system-config-printer#178]
As you can see, the address line is to the right of the smb:// hint.

I also think that the example on the bottom should be aligned to the left because the address must be in English (LTR) and aligned to the left as well.

<img width="512" alt="Screen Shot 2020-08-10 at 10 57 05" src="https://user-images.githubusercontent.com/406826/89762255-bfa18680-daf8-11ea-8c91-95650af581ae.png">

**Comment by zdohnal** [comment]
Hi @yarons ,

thank you for reporting the issue!

system-config-printer is in maintenance mode on my part and the issue doesn't seem critical to fix, so I'll close it.
However, I'm open for a pull request fixing the issue.

**Comment by yarons** [comment]
OK No problem, thanks!
