### ISSUE TITLE
The status of cups still shows idle when the printer has been unplugged

### ISSUE THREAD

**Issue by hugh712** [OpenPrinting/system-config-printer#182]
[ Impact ]
After printers (non-ippusb protocal) have been disconnected, the status of cups still shows "idle" instead of "disabled", so seems the disconnected procedure hasn't worked well.

[ Test Case ]
1. Connect the printer (non-ippusb protocal)(which isn't 070104) with the machine
2. Wait for the status of cups became "Idle" (lpstat -p)
3. Unplug the cable of the printer
4. Check the status of cups again. (lpstat -p)

[Expected result]
The status should show disabled.

[Actual result]
The status shows idle.

[info]
Target:
HP LaserJet Pro203dw
HP Officejet 100 Mobile Printer
HP Officeject 200 Mobile Printer
Brother HL-2250DN
Samsung ML-331x

**Comment by hugh712** [comment]
currently the syspath for udev-configure-printer is too specific level as:

/devices/pci0000:00/0000:00:14.0/usb1/1-5

But current path can be as below for removing

/devices/pci0000:00/0000:00:14.0/usb1/1-5:1.0
or
/devices/pci0000:00/0000:00:14.0/usb1/1-5:1.0/usbmisc/lp0

**Comment by hugh712** [comment]
The idea of my solution[0] is:

1. check if the path provided by map is a subset of removing device path
eg. /devices/pci0000:00/0000:00:14.0/usb1/1-5 is a subset of /devices/pci0000:00/0000:00:14.0/usb1/1-5:1.0

2. check if the exist of this device
eg. stat /sys/devices/pci0000:00/0000:00:14.0/usb1/1-5

3. if this device is not exist, then remove..

[0] https://github.com/hugh712/system-config-printer

**Comment by tillkamppeter** [comment]
Merged PR #183 which fixes this. Thank you very much.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
This continues to affect me in Fedora 36. Was this problem definitely resolved?
