### ISSUE TITLE
how to configure a printer using a command line for a linux vps

### ISSUE THREAD

**Issue by abhishekms123** [OpenPrinting/system-config-printer#184]
please give me proper steps to configure a local dlink printer using a command line

**Comment by zdohnal** [comment]
It depends what do you want to configure... the basic print queue creation is like this:

$ lpadmin -p <print_queue_name> -v <device_uri> -m <everywhere/driverless:<device_uri>/name_from_lpinfo_-l_-m> -E

See CUPS man pages or CUPS documentation for more information.
