### ISSUE TITLE
system-config-printer-applet does not work

### ISSUE THREAD

**Issue by lockywolf** [OpenPrinting/system-config-printer#191]
Hello, everyone.

I'm running `system-config-printer-applet --debug` from the terminal, and getting zero feedback. The only thing that I see is:

```
lockywolf@delllaptop:~/OfficialRepos/slackware-current/source/l/system-config-printer$ system-config-printer-applet --debug
checking for jobs
```

The applet does not appear, nothing happens.

System: Linux 5.4.80, xfce 4.14, cups 2.3.3, system-config-printer 1.5.13

**Comment by zdohnal** [comment]
The applet is run automatically when you print, create a print queue or if a driver is going to be installed during print queue creation.

If you run it by hand, it will just check for existing print jobs and if there is any, the applet is started. If not, it returns to Glib loop and run in the loop till you kill it.

**Comment by lockywolf** [comment]
Could it be just a slightly more user-friendly? I believe, nobody would expect the behaviour you just described. Perhaps, the text of the aforementioned comment could be just added verbatim to the message displayed at program executions?

**Comment by zdohnal** [comment]
The applet is not meant to be run by an user, but by printing system, so user friendliness is out of scope here.
