### ISSUE TITLE
What does "Output Control Common" mean?

### ISSUE THREAD

**Issue by yarons** [OpenPrinting/system-config-printer#196]
I'm not really sure so I can't translate it properly.

The localization UI:
https://translate.fedoraproject.org/translate/system-config-printer/master/he/?q=state%3A%3Ctranslated&offset=1#comments

Origin:
https://github.com/OpenPrinting/system-config-printer/blob/0793877876f61acc43c4a963fde747c3b2134ed1/ppdippstr.py#L207

Thanks.

**Comment by zdohnal** [comment]
Hi,

it is a driver option coming from gutenprint (according the comment) and it was added by @LAfricain . It seems to be explained  [here](https://fossies.org/linux/gutenprint/doc/gutenprint-users-manual.pdf)

**Comment by yarons** [comment]
Understood, it's not a common term in Hebrew but it should be fine.
