### ISSUE TITLE
Bug: 'server-error-internal-error' when Applying Wifi driver to a Canon SELPHY.

### ISSUE THREAD

**Issue by Greatnessguru** [OpenPrinting/system-config-printer#210]
Bug: 'server-error-internal-error' when Applying Wifi driver
to a Canon SELPHY.

Using: system-config-printer 1.5.15.plus_in_uris.
Help > About: system-config-printer 1.5.15
Add > Select Device > Network Printer: Canon SELPHY CP1300(192.168.0.1)
Description: IPP network printer via DNS-SD
Connection: IPP network printer via DNS-SD
Forward
Describe Printer: as expected.
Apply
"CUPS server error
There was an error during the CUPS operation:
'server-error-internal-error'"
OK
Back
Enter device URI: ipp://CP13005d5dd8.local:631/ipp/print
Connection: Driverless IPP (ipp/print)
Forward
Describe Printer: as expected.
Apply
"CUPS server error
There was an error during the CUPS operation:
'server-error-internal-error'"

**Comment by Greatnessguru** [comment]
CUPS 2.2.10, Raspberry Pi OS.

**Comment by zdohnal** [comment]
Hi,

thank you for reporting the issue - would you mind providing CUPS logs? The manual is [here](https://fedoraproject.org/wiki/How_to_debug_printing_problems#CUPS_generic_issue).

Your trigger is 'adding print queue via system-config-printer'.

**Comment by zdohnal** [comment]
And please don't use testing versions of system-config-printer. Are you able to reproduce with normal system-config-printer from repos?

**Comment by Greatnessguru** [comment]
I have just now reverted back to the stock 1.5.11 system-config-printer.
It loads more runtime things than I had, I guess.

**Comment by Greatnessguru** [comment]
I just now reproduced the same Bug error the same two times as before.

**Comment by zdohnal** [comment]
Please provide cups logs, the steps how to do it are in the link from my first comment.

**Comment by Greatnessguru** [comment]
E [25/Jan/2021:02:21:22 -0500] [CGI] Unable to create PPD file: No IPP
attributes.
E [25/Jan/2021:02:22:20 -0500] [CGI] Unable to create PPD file: No IPP
attributes.
E [25/Jan/2021:02:22:20 -0500] copy_model: empty PPD file
E [25/Jan/2021:02:22:20 -0500] [Client 33] Returning IPP
server-error-internal-error for CUPS-Add-Modify-Printer
(ipp://localhost/printers/Canon-SELPHY-CP1300-WiFi) from localhost.
E [25/Jan/2021:02:22:30 -0500] [CGI] Unable to create PPD file: No IPP
attributes.
E [25/Jan/2021:02:22:30 -0500] copy_model: empty PPD file
E [25/Jan/2021:02:22:30 -0500] [Client 36] Returning IPP
server-error-internal-error for CUPS-Add-Modify-Printer
(ipp://localhost/printers/Canon-SELPHY-CP1300-WiFi) from localhost.
E [25/Jan/2021:02:23:00 -0500] [CGI] Unable to create PPD file: No IPP
attributes.
E [25/Jan/2021:02:23:27 -0500] [CGI] Unable to create PPD file: No IPP
attributes.
E [25/Jan/2021:02:23:27 -0500] copy_model: empty PPD file
E [25/Jan/2021:02:23:27 -0500] [Client 41] Returning IPP
server-error-internal-error for CUPS-Add-Modify-Printer
(ipp://localhost/printers/printer) from localhost.
E [25/Jan/2021:02:23:37 -0500] [CGI] Unable to create PPD file: No IPP
attributes.
E [25/Jan/2021:02:23:37 -0500] copy_model: empty PPD file
E [25/Jan/2021:02:23:37 -0500] [Client 36] Returning IPP
server-error-internal-error for CUPS-Add-Modify-Printer
(ipp://localhost/printers/printer) from localhost.

**Comment by Greatnessguru** [comment]
I used nano to set Loglevel to debug2.
Do I need to restart CUPS for it to take effect?

E [25/Jan/2021:03:31:00 -0500] [CGI] Unable to create PPD file: No IPP
attributes.
E [25/Jan/2021:03:31:25 -0500] [CGI] Unable to create PPD file: No IPP
attributes.
E [25/Jan/2021:03:31:25 -0500] copy_model: empty PPD file
E [25/Jan/2021:03:31:25 -0500] [Client 63] Returning IPP
server-error-internal-error for CUPS-Add-Modify-Printer
(ipp://localhost/printers/Canon-SELPHY-CP1300-2) from localhost.
E [25/Jan/2021:03:31:35 -0500] [CGI] Unable to create PPD file: No IPP
attributes.
E [25/Jan/2021:03:31:35 -0500] copy_model: empty PPD file
E [25/Jan/2021:03:31:35 -0500] [Client 66] Returning IPP
server-error-internal-error for CUPS-Add-Modify-Printer
(ipp://localhost/printers/Canon-SELPHY-CP1300-2) from localhost.
E [25/Jan/2021:03:32:24 -0500] [CGI] Unable to create PPD file: No IPP
attributes.
E [25/Jan/2021:03:32:37 -0500] [CGI] Unable to create PPD file: No IPP
attributes.
E [25/Jan/2021:03:32:37 -0500] copy_model: empty PPD file
E [25/Jan/2021:03:32:37 -0500] [Client 71] Returning IPP
server-error-internal-error for CUPS-Add-Modify-Printer
(ipp://localhost/printers/printer) from localhost.
E [25/Jan/2021:03:32:47 -0500] [CGI] Unable to create PPD file: No IPP
attributes.
E [25/Jan/2021:03:32:47 -0500] copy_model: empty PPD file
E [25/Jan/2021:03:32:47 -0500] [Client 66] Returning IPP
server-error-internal-error for CUPS-Add-Modify-Printer
(ipp://localhost/printers/printer) from localhost.
E [25/Jan/2021:03:33:24 -0500] [CGI] Unable to create PPD file: No IPP
attributes.
E [25/Jan/2021:03:33:24 -0500] copy_model: empty PPD file
E [25/Jan/2021:03:33:24 -0500] [Client 76] Returning IPP
server-error-internal-error for CUPS-Add-Modify-Printer
(ipp://localhost/printers/printer) from localhost.
E [25/Jan/2021:03:33:34 -0500] [CGI] Unable to create PPD file: No IPP
attributes.
E [25/Jan/2021:03:33:34 -0500] copy_model: empty PPD file
E [25/Jan/2021:03:33:34 -0500] [Client 66] Returning IPP
server-error-internal-error for CUPS-Add-Modify-Printer
(ipp://localhost/printers/printer) from localhost.

**Comment by zdohnal** [comment]
Do you see the printer via ```lpinfo -v```?

Can you add the print queue via lpadmin?

```
$ lpadmin -p test -v ipp://CP13005d5dd8.local:631/ipp/print -m driverless:ipp://CP13005d5dd8.local:631/ipp/print -E
```

**Comment by Greatnessguru** [comment]
pi@raspberrypi:~ $ lpinfo -v
network http
network socket
direct vnc:/
network ipps
network beh
file cups-brf:/
network ipp
network lpd
direct hp
network https
direct hpfax
network
dnssd://Canon%20SELPHY%20CP1300._ipp._tcp.local/?uuid=8c6b4304-4b0f-4943-b7d9-7438b75d5dd8
network ipp://CP13005d5dd8.local:631/ipp/print
pi@raspberrypi:~ $ lpadmin -p test -v
ipp://CP13005d5dd8.local:631/ipp/print -m
driverless:ipp://CP13005d5dd8.local:631/ipp/print -E
lpadmin: Unable to open PPD "/tmp/01fbb600ef051": Missing PPD-Adobe-4.x
header on line 0.
pi@raspberrypi:~ $

**Comment by zdohnal** [comment]
Ok, so it is not a s-c-p bug. The device is accessible on the network, but creating a driverless queue fails for some reason (printer bug  or driver bug). Please report to cups-filters project.
