### ISSUE TITLE
Canon PIXMA G2160/G2060 drivers not working.

### ISSUE THREAD

**Issue by McBruno712** [OpenPrinting/system-config-printer#256]
I have a PIXMA G2160 (but gets detected as a G2060), if I install the recommended drivers the printer does not print, but if I manually install [these drivers](https://in.canon/en/support/PIXMA%20G2060/model) (which are for the G2060) it works perfectly, it also works with [these drivers for the G2160](https://www.cla.canon.com/cla/en/support/consumer/printers_multifunction/g_series_inkjet_printers/pixma_g2160#driversAndSoftwareTab) (which I suspect are the same).

**Comment by zdohnal** [comment]
Hi @McBruno712 ,

there are several things in play to mention:

- system-config-printer (s-c-p) cannot automatically install drivers which aren't in distribution (3rd party drivers) - you always have to do it manually
- AFAIK s-c-p can install a printer with a 3rd party driver if the driver is accessible via CUPS (it is listed when you do ```lpinfo -m```)

So if the driver isn't installed as CUPS driver (isn't detectable by CUPS), s-c-p cannot install a printer with it so it uses the closest driver found.

So the key question is - is the Canon driver seen in the CUPS output?

**Comment by zdohnal** [comment]
No reply for 3 weeks, closing.
