### ISSUE TITLE
FR: UI: filter printer models by Ctrl+F

### ISSUE THREAD

**Issue by mikhailnov** [OpenPrinting/system-config-printer#257]
When there are a lot of models of printers in the list, a search or a filter may be required. It is possible to search by ctrl+f, but it searches only by the beginning of lines.
E.g. search query "foo" will not find the line "loo-foo". It would be nice to filter lines.
![2022-01-19_13-41](https://user-images.githubusercontent.com/15802528/150115026-cd48f0fb-6dce-4fd5-b449-85fc54736d4e.png)

**Comment by zdohnal** [comment]
Hi @mikhailnov ,

I don't currently plan to focus on features in s-c-p, especially connected to drivers which go away in year or so - I keep s-c-p in maintain mode, but willing to review/test/accept PRs or add a co-maintainer who would want to implement the feature.
