### ISSUE TITLE
Please consider updating autotool scripts.

### ISSUE THREAD

**Issue by TinySnow** [OpenPrinting/system-config-printer#282]
Hello, I'm from ArchRISC-V Team, a community porting Arch Linux software to RISC-V architecture.

#### Description

While packaging `system-config-printer`, we found an error.

<details>

<summary>Error information</summary>

```bash
checking build system type... ./config.guess: unable to guess system type

This script, last modified 2015-01-01, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
and
  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD

If the version you run (./config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2015-01-01

uname -m = riscv64
uname -r = 5.18.16-arch1-1
uname -s = Linux
uname -v = #1 SMP PREEMPT_DYNAMIC Wed, 03 Aug 2022 11:25:04 +0000

/usr/bin/uname -p = unknown
/bin/uname -X     = 

hostinfo               = 
/bin/universe          = 
/usr/bin/arch -k       = 
/bin/arch              = 
/usr/bin/oslevel       = 
/usr/convex/getsysinfo = 

UNAME_MACHINE = riscv64
UNAME_RELEASE = 5.18.16-arch1-1
UNAME_SYSTEM  = Linux
UNAME_VERSION = #1 SMP PREEMPT_DYNAMIC Wed, 03 Aug 2022 11:25:04 +0000
configure: error: cannot guess build type; you must specify one
```

</details>

#### Solved

- Added `autoreconf` in the `prepare()` function in the `PKGBUILD`. Here is the code:

```bash
prepare() {
  autoupdate
  autoreconf -fiv
}
```

- However, after adding code, it occurred bash scripts errors (Related to m4 macros not expanding), so I added `autoconf-archive` to `makedepends` according to my previous packaging experience. Finally, it solved.

### Advice

- Please consider updating the configure script tools(Especially `config.guess` file). As part of our duty, we do suggest our upstreams doing this once and for all instead.

Sincerely thanks.

:)

**Comment by zdohnal** [comment]
I've updated config.sub and config.guess as we did for other OpenPrinting projects when people reported configuration problems on RiSC. I hope it fixes it.
