### ISSUE TITLE
ValueError: Namespace Handy not available

### ISSUE THREAD

**Issue by TKperson** [OpenPrinting/system-config-printer#283]
### Description

I installed `system-config-printer` from [Arch extra](https://archlinux.org/packages/extra/x86_64/system-config-printer/). Whenever I ran `system-config-printer`, I get this error:

```
Traceback (most recent call last):
  File "/usr/share/system-config-printer/system-config-printer.py", line 51, in <module>
    gi.require_version('Handy', '1')
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Handy not available
```

The error looks very similar to #276. Instead of the "Handy" package that is causing the error, the package that's causing the error in the issue was "Notify".

I wasn't able to locate the library that "Handy" is in, and I'm not able to using `system-config-printer`.

How do I fix this error?

### System environments

OS: Arch Linux x86_64
Kernel: 5.19.4-arch1-1
system-config-printer version: 1.5.17-1

**Comment by jayp0521** [comment]
+1 getting this error

**Comment by jayp0521** [comment]
https://github.com/OpenPrinting/system-config-printer/blob/7a1bf8dc9111deb3f43ec9bcb27d287e404e1bb8/system-config-printer.py#L50-L51

looking at source code,

installing `libhandy` seems to have made issue go away for me

**Comment by zdohnal** [comment]
Hi,

I'm sorry about this - I ran s-c-p during testing only on GNOME, where this library is installed. libhandy is optional, so the ```gi.require``` has to be in ```try:`` scope.
