### ISSUE TITLE
1.5.18 signed incorrectly ?

### ISSUE THREAD

**Issue by fenrus75** [OpenPrinting/system-config-printer#286]
as part of distro automation we check gpg signatures on upstream sources and for the 1.5.18 release we get gpg complaining:

Exception: gpg: keybox '/tmp/tmp.gpghomeimk3m5kc/pubring.kbx' created
gpg: key E4522DCC9B246FF7: no valid user IDs
gpg: this may be caused by a missing self-signature
gpg: Total number processed: 1
gpg:           w/o user IDs: 1

Can this be looked into? I wouldn't want to ship a package that is signed but fails its signature obviously

**Comment by zdohnal** [comment]
No  response for a month, closing.
