### ISSUE TITLE
Every version after 1.5.15 fails: `./configure: line 3133: syntax error: unexpected word (expecting ")")`

### ISSUE THREAD

**Issue by PureTryOut** [OpenPrinting/system-config-printer#287]
The only commands I run here are the following:

```sh
./bootstrap
./configure \
    --build=$CBUILD \
    --host=$CHOST \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var
```

**Comment by zdohnal** [comment]
@PureTryOut what is your values for $CBUILD and $CHOST? I can't reproduce the issue on the latest HEAD.

Are you trying this in your cloned repo of this project? What OS do you use?

**Comment by PureTryOut** [comment]
This is work to update the Alpine Linux package. So it doesn't use a cloned version of the repo but rather the last release tarball.

Both `$CBUILD` and `$CHOST` are set to `x86_64-alpine-linux-musl`.

**Comment by zdohnal** [comment]
@PureTryOut the release tarball has a pregenerated ```configure```, does the pregenerated one work for you? Because if you run ```./bootstrap```, you generate a new ```configure``` based on your local tools, so the lines in the error message don't match and I can't check them...

Still I'm not able to reproduce, even with your values...

**Comment by PureTryOut** [comment]
I... Totally missed that it already had a `configure` :scream:  That works like a dream, thanks! Since you can't reproduce this and the pregenerated one works fine I'll close this issue.
