### ISSUE TITLE
Exception on passing two argument to debugprint() which only takes one

### ISSUE THREAD

**Issue by crass** [OpenPrinting/system-config-printer#291]
https://github.com/OpenPrinting/system-config-printer/blob/9f35bbaf219e076b1b627de980fb79dfafd97497/options.py#L426

This line throws an exception because `debugprint()` takes only one argument. It should instead be something like: `debugprint("Selecting from choices: %s" % supported[0])`

**Comment by zdohnal** [comment]
@crass thank you for the report!
