### ISSUE TITLE
Epson 520 issue - Not printing

### ISSUE THREAD

**Issue by nhlinux** [OpenPrinting/system-config-printer#292]
Epson 520 printer linked via WIFI. to Dell Inspiron 3593 laptop running on Linux Mint 21. After running print test, printer spits out sheets continuously. The sheets are blank white except for some sheets that have random texts on them.

Thanks.

[troubleshoot.txt](https://github.com/OpenPrinting/system-config-printer/files/9909758/troubleshoot.txt)

**Comment by zdohnal** [comment]
Hi @nhlinux ,

system-config-printer probably found the only installed driver similar to your model - Epson Workforce 500 from gutenprint - which doesn't produce the format acceptable by your printer (based on the printer's behavior you've described).

Is your printer Epson Workforce 520? Or Epson XP 520?

Epson XP 520 has AirPrint support, so you don't have to install the printer at all and just use it as it is - you should see your printer in ```avahi-browse -avrt``` output and in ```lpstat -e```, but not in ```lpstat -a```. If the printer is seen in those outputs but not in the application, file an issue to application.

Epson Workforce 520 does not have Airprint, but there is a driver package which probably don't have installed - I'm not sure how it is called in Linux Mint, but in Fedora it is ```epson-inkjet-printer-escpr```. The driver from the package could help

**Comment by zdohnal** [comment]
No response for a month, closing...

**Comment by nhlinux** [comment]
Epson Workforce 520 .
