### ISSUE TITLE
make view print queue default action in favour of properties a right-click option

### ISSUE THREAD

**Issue by stefan123t** [OpenPrinting/system-config-printer#311]
Dear OpenPrinting team,
I have been using system-config-printer for ages / more than a decade.
However it always struck me by surprise that the basic action of "View print queue" is only available via the `Strg+F` shortcut or right-click menu. Whereas the much less often required configuration properties dialog comes up on the default double click action.
In order to make the application more useful to new users and adhere to general standards I would suggest to make "View print queue" the default double click and also consider switching the positions of the two entries "Properties" and "View print queue" in the right-click menu as usually the default action should come first.
Kind regards,
Stefan

**Comment by zdohnal** [comment]
Hi Stefan,

system-config-printer is a printer configuration tool, so IMO it makes sense to have configuration widget as a default action.

Either way, thank you for the feedback!
