### ISSUE TITLE
Error Printing

### ISSUE THREAD

**Issue by tech64linux** [OpenPrinting/system-config-printer#330]
I use system-config-printer with Xubuntu.
It's happened, when i select to print even pages only, it print only odd pages.
My printer is HP Laserjet Pro M15W.
 Is this a bug of program ?
  Thanks, Fausto

**Comment by zdohnal** [comment]
system-config-printer is configuration tool, not printing daemon - please read https://github.com/OpenPrinting/cups/blob/master/REPORTING_ISSUES.md , get the needed data, file the issue at OpenPrinting/CUPS Github and provided needed data.
