### ISSUE TITLE
/usr/share/system-config-printer/scp-dbus-service.py:602: DeprecationWarning: Gdk.threads_enter is deprecated

### ISSUE THREAD

**Issue by istenburg** [OpenPrinting/system-config-printer#363]
When I start the printer, I get the following error message.
```09:08:18 scp-dbus-servic:   Gdk.threads_enter ()
09:08:18 scp-dbus-servic: /usr/share/system-config-printer/scp-dbus-service.py:602: DeprecationWarning: Gdk.threads_enter is deprecated`

**Comment by zdohnal** [comment]
It is the same as #126 . s-c-p contains bunch of old GTK stuff, which can be updated before they are removed from gtk - but it is only warning at the moment.

There is PR #129 attempting to get rid of the warnings, but threading is sensitive part of any application and I haven't had time to test the PR thoroughly.
