### ISSUE TITLE
Better appearance of main window

### ISSUE THREAD

**Issue by TomaszGasior** [OpenPrinting/system-config-printer#69]
1. Add frame to printer list in main window.
[PrintersWindow.ui-frame.patch.txt](https://github.com/zdohnal/system-config-printer/files/1150371/PrintersWindow.ui-frame.patch.txt)
![screenshot](https://user-images.githubusercontent.com/1395027/28239857-d21317f4-6975-11e7-89bd-70ffe22497e9.png)

2. Move "Lock"/"Unlock" button from menubar to toolbar.

**Comment by zdohnal** [comment]
Hi Tomasz,

thank you for contributing. What exactly do you suggest by this issue? Would you mind creating pull request for it?

**Comment by TomaszGasior** [comment]
I am not good C/Python/GTK programmer. I create websites. ;) So I would not like to create pull request to your code.

Please see screenshots. There are a lot of GTK themes with menu bar with dark color, that matches to titlebar color (sorry for my English). It is ugly, if you add button to menubar. It seems to me it would be better, if you add "Lock"/"Unlock" button to toolbar.

Also, you can add "frame" CSS class to printers list to get better appearance. There are a lot of apps that use "frame" CSS class to visually separate main window elements. See my screenshot in first post. Window of "system-config-printer" on the left side is in current state. In window on the right side I added "frame" CSS class by built-in GTK inspector.

**Comment by zdohnal** [comment]
Ad Lock/Unlock - I think gnome-control-center decides position of this button, I can not do any more about it.
Ad frame - I am sorry, but I do not see any difference between these two windows (just the one on the right is highlighted, because it's active). Could you highlight changes which I should see?
If there isn't any visible/functional improvement, I do not think as necessary to include such change into project (meaning closing this issue).

**Comment by TomaszGasior** [comment]
Please, compare.

Current state:
![before](https://user-images.githubusercontent.com/1395027/28422527-97e5670c-6d68-11e7-9360-d1e6b707db47.png)

When you add "frame" CSS class to printers list:
![after](https://user-images.githubusercontent.com/1395027/28422554-a9decfe8-6d68-11e7-8da8-7b27a2521aed.png)

**Comment by zdohnal** [comment]
Not critical issue - I will not pursue of fixing it, but I'll accept any patches regarding the issue.
