### ISSUE TITLE
The icon label and contextual menu and windows title is not translated

### ISSUE THREAD

**Issue by LAfricain** [OpenPrinting/system-config-printer#84]
Hello,
Till I modified the ppdippstr.py file, the label of the icon and the title of the window is in English now. I can't found the string in the sources.
See the captures:

![printers](https://user-images.githubusercontent.com/19690477/33733491-3e88f7ec-db8a-11e7-963f-db7d0e5b9773.png)
![printers2](https://user-images.githubusercontent.com/19690477/33733492-3ed840a4-db8a-11e7-8318-eea9056253f4.png)

**Comment by zdohnal** [comment]
Hi,
if you can find it in sources, can you add translation then? Let's keep it in #79 .

**Comment by LAfricain** [comment]
Sorry I did a typing error : I **can't** find the string in the sources! (I modified the first message).
You to know, for my test I just replace the actual ppdippstr.py of my system (Ubuntu 16.04) with the new. And the actual mo with the new too. Maybe you changed the name of the window in the new version?

**Comment by zdohnal** [comment]
I think I found cause - you cannot mix tabs and spaces in python code - ppdippstr.py probably failed and this is probably outcome of it.

**Comment by LAfricain** [comment]
Please reopen this issue, it is not solved :)

**Comment by zdohnal** [comment]
IMO s-c-p doesn't have this name in its power - this name 'Printers' is set by control-center or a program, which opens s-c-p.

**Comment by LAfricain** [comment]
Yes it is possible but why it happens after changing the ppdippstr.py file?

**Comment by LAfricain** [comment]
I was a mistake to close it sorry!!

**Comment by LAfricain** [comment]
I experienced the same on LXDE, in the menu launcher, the name is in English.

**Comment by LAfricain** [comment]
Really strange, I change tu ui language to italian, and now it is no more Printers, but Stampanti!

**Comment by LAfricain** [comment]
Ubuntu 20.04 solved

**Comment by zdohnal** [comment]
Thank you for letting me know!

**Comment by LAfricain** [comment]
You welcome!
Did you see my last very annoying issue report #179 ? Sometimes github people (I don't know why) doesn't have notification about my issues report.
And have you some intention to merge this pull request: #117 ?
